### ISSUE TITLE
Scores appears twice in URL

### ISSUE THREAD

**Issue by ToAruShiroiNeko** [halfak/Objective-Revision-Evaluation-Service#41]
YuviPanda noticed that the url structure has "scores" repeated when load balanced ores is accessed:

http://ores-lb.wmflabs.org/scores/scores/enwiki/?models=reverted&revids=4567454

<YuviPanda> I think it's because ores sets both an application root and a url prefix

**Comment by halfak** [comment]
This is not a bug, but a configuration issue.

**Comment by halfak** [comment]
Just to clarify, "application_root" tells ORES what to expect in the URL.  For example, the hosting webserver may specify a prefix and ORES will need to know that prefix to set cookies and other things appropriately.

"url_prefix", on the other hand, tells ORES' flask app to set it's own prefix.  

To solve this problem, set both application_root and url_prefix to "".

**Comment by he7d3r** [comment]
Was this fixed (I don't see the duplicated scores)?
