### ISSUE TITLE
Error responses should not return HTTP Status code 200

### ISSUE THREAD

**Issue by yuvipanda** [halfak/Objective-Revision-Evaluation-Service#44]
HTTP Status code 200 means success, ORES seems to be returning that for failures too. Should be an error in the 4xx range for client errors and 5xx range for server ones.

**Comment by halfak** [comment]
They would, but jsonp doesn't work then.

**Comment by yuvipanda** [comment]
We shouldn't be using JSONP. CORS works just as good and can do all the things JSONP does and then some :)

**Comment by halfak** [comment]
Tools are already using jsonp.  I appreciate your vision of the future, but we're at least two steps away -- and we should still support jsonp.  

Also, this bug is invalid because we do return reasonable status codes.

**Comment by halfak** [comment]
E.g. http://ores.wmflabs.org/scores/enwiksdasdasd/

**Comment by yuvipanda** [comment]
Fair enough. I've opened #45

**Comment by he7d3r** [comment]
@halfak @yuvipanda: so, I'm having an issue which seems related to this. If I run
```javascript
$.ajax( {
	url: '//ores.wmflabs.org/scores/metawiki/',
	dataType: 'jsonp'
} )
.done(function(){ console.log('done') })
.fail(function(){ console.log('fail') });
```
on Meta-wiki I don't get "done" or "fail" either (due to `HTTP/1.1 404 NOT FOUND`?). However, I can access the URL in the browser to see 
```javascript
{
  "error": {
    "code": "not found",
    "message": "No scorers available for metawiki"
  }
}
```
I need to get the error code/message so that I can show something reasonable for the users.
